server:
    address: :2002
    model: debug

#数据库配置
db:
  dialects: mysql
  host: display-ota.mysql.rds.aliyuncs.com
  port: 3306
  db: mail
  username: mail
  password: Mail20240906
  charset: utf8
  #最大空闲数
  maxIdle: 50
  #最大连接数
  maxOpen: 100

# #redis配置
# redis:
#   address: 127.0.0.1:6379
#   password:

#log配置
log:
  path: log/
  name: mailLog.log
  model: console

imageSettings:
  uploadDir: /static/upload/
