server:
    address: :2002
    model: debug

#数据库配置
#  host: display-ota.mysql.rds.aliyuncs.com
db:
  dialects: mysql
  host: {DB_HOST}
  port: {DB_PORT}
  db: {DB_NAME}
  username: {DB_USERNAME}
  password: {DB_PASSWORD}
  charset: utf8
  #最大空闲数
  maxIdle: 50
  #最大连接数
  maxOpen: 100

# #redis配置
# redis:
#   address: 127.0.0.1:6379
#   password:

#log配置
log:
  path: log/
  name: mailLog.log
  model: console

imageSettings:
  uploadDir: /static/upload/
